# Generated by Django 3.0.8 on 2020-08-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_auto_20200825_2110'),
        ('accounts', '0003_auto_20200729_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite',
            field=models.ManyToManyField(to='competitions.Lomba'),
        ),
    ]
