# Generated by Django 3.0.8 on 2020-08-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200829_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='participant_level',
            field=models.CharField(choices=[('sd', 'SD'), ('smp', 'SMP'), ('sma', 'SMA'), ('univ', 'Universitas'), ('umum', 'Umum')], default='umum', max_length=50),
        ),
    ]
