# Generated by Django 3.0.8 on 2020-09-09 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0018_auto_20200909_2112'),
        ('accounts', '0008_profile_subscribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subscribe',
        ),
        migrations.AddField(
            model_name='profile',
            name='subscribe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.Kategori'),
        ),
    ]
