# Generated by Django 3.0.8 on 2020-09-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0018_auto_20200909_2112'),
        ('accounts', '0009_auto_20200909_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subscribe',
        ),
        migrations.AddField(
            model_name='profile',
            name='subscribe',
            field=models.ManyToManyField(to='competitions.Kategori'),
        ),
    ]
