# Generated by Django 3.0.8 on 2020-07-20 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_auto_20200720_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lomba',
            name='inactive',
        ),
    ]
