# Generated by Django 3.0.8 on 2020-07-20 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_remove_lomba_inactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='lomba',
            name='inactive',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
