# Generated by Django 3.0.8 on 2020-08-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_kategori_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lomba',
            old_name='inactive',
            new_name='deadline',
        ),
        migrations.AddField(
            model_name='lomba',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lomba',
            name='competitions_level',
            field=models.CharField(choices=[('lokal', 'Lokal'), ('nasional', 'Nasional'), ('internasional', 'Internasional')], default='nasional', max_length=50),
        ),
        migrations.AddField(
            model_name='lomba',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='lomba',
            name='owner_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='lomba',
            name='participant_level',
            field=models.CharField(choices=[('sd', 'SD'), ('smp', 'SMP'), ('sma', 'SMA'), ('univ', 'Universitas'), ('umum', 'Umum')], default='umum', max_length=50),
        ),
        migrations.AddField(
            model_name='lomba',
            name='visited',
            field=models.IntegerField(default=0),
        ),
    ]
