# Generated by Django 3.0.8 on 2020-08-22 06:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_auto_20200807_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='lomba',
            name='tanggalpelaksanaan',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
