# Generated by Django 3.0.8 on 2020-08-31 10:08

from django.db import migrations
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('competitions', '0008_auto_20200825_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lomba',
            name='tags',
            field=taggit_autosuggest.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
