# Generated by Django 3.0.8 on 2020-09-01 15:47

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_auto_20200831_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='lomba',
            name='description2',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='lomba',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
