# Generated by Django 3.0.8 on 2020-09-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0011_remove_lomba_description2'),
    ]

    operations = [
        migrations.AddField(
            model_name='lomba',
            name='jumlahhadiah',
            field=models.DecimalField(decimal_places=2, default=1000000, max_digits=9),
            preserve_default=False,
        ),
    ]
