# Generated by Django 3.0.8 on 2020-09-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0012_lomba_jumlahhadiah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lomba',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
