# Generated by Django 3.0.8 on 2020-09-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0014_auto_20200905_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lomba',
            name='deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='lomba',
            name='tanggalpelaksanaan',
            field=models.DateTimeField(),
        ),
    ]
