# Generated by Django 3.0.8 on 2020-09-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0016_lomba_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lomba',
            name='active',
        ),
        migrations.AlterField(
            model_name='lomba',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='lomba',
            name='tanggalpelaksanaan',
            field=models.DateField(),
        ),
    ]
