# Generated by Django 3.0.8 on 2020-09-09 14:12

from django.db import migrations
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('competitions', '0017_auto_20200907_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lomba',
            name='tags',
            field=taggit_autosuggest.managers.TaggableManager(blank=True, help_text='ex: Teknologi, Inovasi... (Pisahkan dengan Koma)', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
