# Generated by Django 3.0.8 on 2020-09-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0018_auto_20200909_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lomba',
            name='contact',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='lomba',
            name='description',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='lomba',
            name='jumlahhadiah',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='lomba',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='lomba',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
